version: '3.8'
services:
  library_nestech:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=library_nestech
      - MYSQL_USER=nestech
#      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - '3306:3306'

#  volumns:
#     - ./docker/data:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local